config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :rooms do
    resources :messages
  end
  get 'rooms/index'
  
  post "/hello", to: "pages#hello"
  root "rooms#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  has_many :messages

  after_create_commit { broadcast_append_to room }
end

app/models/room.rb
class Room < ApplicationRecord
    validates_uniqueness_of :name
    scope :public_rooms, -> {where(is_private: false)}

    after_create_commit { broadcast_append_to "rooms" }
    has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :article)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    def create
        @message = Message.create(body: msg_params[:body], room_id: params[:room_id], user: msg_params[:user])
    end
    private
    def msg_params
        params.require(:message).permit(:body, :user)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def hello

  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @room = Room.new
    @rooms = Room.public_rooms

    render 'index'
  end

  def show
    @single_room = Room.find(params[:id])

    @room = Room.new
    @rooms = Room.public_rooms

    @message = Message.new
    @messages = @single_room.messages.order(created_at: :asc)

    render 'index'
  end

  def create
    @room = Room.create(name: params["room"]["name"])
  end

  def destroy
    @room = Room.find(params[:id])
    Message.destroy_by(room: @room)
    @room.destroy
    redirect_to action: "index"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Article:</strong>
    <%= article.article %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :article, style: "display: block" %>
    <%= form.text_area :article %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", article %>
    </p>
  <% end %>
</div>

<%= link_to "New article", new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Turbochat</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/_new_message_form.html.erb
<div class="form-group msg-form">
    <%= form_with(model: [@single_room, @message], remote: true, class: 'd-flex',
    data: {controller: "reset-form", action: "turbo:submit-end->reset-form#reset"}) do |f| %>
    <%= f.text_field :user, id: 'chat-user', class: 'form-control msg-content', autocomplete: 'off', placeholder: 'Name' %>
    <%= f.text_field :body, id: 'chat-text', class: 'form-control msg-content', autocomplete: 'off', placeholder: 'Message' %>
    <%= f.submit data: {disable_with:false}, class: 'btn btn-primary' %>
    <% end %>
</div>

app/views/layouts/_new_room_form.html.erb
<%= form_with(model: @room, remote: true, class: 'd-flex',
 data: {controller: "reset-form", action: "turbo:submit-end->reset-form#reset"}) do |f| %>
    <%= f.text_field :name, class: 'form-control', autocomplete: 'off' %>
    <%= f.submit data: {disable_with: false} %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Video</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- CSS -->
    <style>
      <%= ".msg-#{@user}" %> {
        background-color: lightblue !important;
        padding: 10px;
      }

      <%= ".cont-#{@user}" %> {
      display:flex;
        justify-content: flex-end;
        padding: 10px;
      }
    </style>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  
  </body>
</html>

app/views/messages/_message.html.erb
<div class="cont-<%= message.user%>">
    <div class="message-box msg-<%= message.user%>">
    <h6><%= message.user%></h6>
    
    <%= message.body%>
    </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<%= button_to "Say Hello", hello_path %>

app/views/rooms/_room.html.erb
<div>
    <ul>
        <li>
            <%= link_to room.name, room %>
        </li>
    </ul>
    
</div>

app/views/rooms/index.html.erb
<div id="chatroom_container" class="row bg-dark text-light">
    <div id="side_panel" class="col-md-4 col-sm-4">
        <h4>
            Rooms
        </h4>
        <%= render 'layouts/new_room_form' %>
        
        <%= turbo_stream_from "rooms"%>
        <div id="rooms" class="text-decoration-none">
            <%= render @rooms %>
        </div>
       
       
        
    </div>
    <div id="room_container"
    class="col-md-8 col-sm-8 bg-dark text-light">
        <% if @single_room %>
            <div id="single_room">
                <h4 class="text-center"> 
                    <%= @single_room.name %> 
                    <%= button_to "Clear", @room.id, method: :delete %>
                </h4>
                <%= turbo_stream_from @single_room %>
                <div id="messages" data-controller="scroll" >
                    <% if @messages %>
                    <%= render @messages %>
                    <% end %>
                </div>
                <%= render 'layouts/new_message_form' %>
            </div>
        <% end %>
    </div>
</div>